#!/bin/bash
# Real bynow

ABINIT_BASE="_o_DS"

if [ $# -lt 3 ]
then
    echo "Usage: qMerge: <# of k-points> <abinit output file name> <abinit base name>"
    exit
else
    echo "Number of k-points specified: $1"
fi

echo "mergelog_byk $(($1)) $2"
mergelog_byk_17 $(($1)) $2

#mergeNonloc $(($1)) $2


echo "Removing redundant files..."

rm -rf *.nonlocal
rm -rf nonlocal_byk_log
mkdir nonlocal_byk_log
mv *kpt*.log nonlocal_byk_log/.

generate_XSF $2 $3 1 0.00001
generate_XSF $2 $3 3 0.00001

#if [ $# -eq 5 ]
#then
#  if [ $5 -eq 1 ]
#  then
#    rm *WFK* 
#  fi
#fi

echo "DONE!"
