#!/bin/sh

ACF_name="ACF.dat"

if [ $# -eq 2 ]
then
  echo "Files file name: $1"
  echo "ABINIT output file name: $2"
  echo "bader output name: ACF.dat"
elif [ $# -eq 3 ]
then
  echo "Files file name: $1"
  echo "ABINIT output file name: $2"
  echo "bader output name: $3"
  ACF_name=$3
else
  echo "Usage: <ABINIT files file name> <ABINIT output file name> optionally: <Bader output file name (ACF.dat if not renamed)>"
  exit 1
fi

FILES_FILE_name=$1
OUT_FILE_name=$2
BADER_name="Bader"


if [ ! -f $FILES_FILE_name ]
then
  echo "File $FILES_FILE_name not found!"
  exit 1
fi

if [ ! -f $OUT_FILE_name ]
then
  echo "File $OUT_FILE_name not found!"
  exit 1
fi

if [ ! -f $ACF_name ]
then
  echo "File $ACF_name not found!"
  exit 1
fi

if [ -d $BADER_name ]
then
  echo "Direcotry Bader already exists"
  echo "This script will delete the original Bader folder"
  read -p "Press enter to continue or Ctrl+c to exit"
  rm -rf Bader
fi

prepareApe $FILES_FILE_name $OUT_FILE_name $ACF_name
