#!/bin/sh
if [ $# -le 2 ]
then
  echo "Usage: <Number of k-points> <ABINIT output file> <ABINIT o_ base name>"
fi

if [ $# -gt 2 ]
  then
  outfile=$2
  o_filebase=$3
  nkpoints=$1
  kpo=1
  while [ $kpo -le $nkpoints ]  
  do  
     qnonlocal17_by_k $outfile $o_filebase 1 $kpo
     #sleep 1
     qnonlocal17_by_k $outfile $o_filebase 3 $kpo
     #sleep 1
     kpo=$(( kpo+1 ))   
  done
fi
