#!/bin/sh
# Real bynow

echo "This program requires no input."
echo "This program will run APE calculation based on Bader input files in Bader directory."
echo "Please make sure you have Bader directory and correct ionicity subdirectory."
echo "For example, to run 100% ionicity for the Al1 site in a crystal structure, this program requires Bader/I100/Al1/inp.ape file."

read -p "Press Enter to continue..." 

if [ ! -f Bader_Info ]
then
  echo "File Bader_Info not exist."
  echo "Looks like you did not generate your APE input files with prepareApe."
  echo "You can still manually generate Bader_Info, it only needs to include all sites of atom, separated by line."
  echo "For example, for NaCl (one Na site and one Cl site), the Bader Info should look like:"
  echo "Na1"
  echo "Cl1"
  echo "The order of sites does not matter."
  exit 1
fi

SITE_COUNT=`head -1 Bader_Info`
CURRENT_PATH=`pwd`
#echo "Current directory: $CURRENT_PATH"
echo "There are $SITE_COUNT sites in your crystal structure."

i=1
while [ $i -le $SITE_COUNT ]
do
  i=$(( i+1 ))
  SITE_ID=`head -n $i Bader_Info | tail -1`
  I100_DIRECTORY_PATH="Bader/I100/${SITE_ID}"
  I75_DIRECTORY_PATH="Bader/I75/${SITE_ID}"
  I50_DIRECTORY_PATH="Bader/I50/${SITE_ID}"
  I25_DIRECTORY_PATH="Bader/I25/${SITE_ID}"
  I100_INP_PATH="Bader/I100/${SITE_ID}/inp.ape"
  I75_INP_PATH="Bader/I75/${SITE_ID}/inp.ape"
  I50_INP_PATH="Bader/I50/${SITE_ID}/inp.ape"
  I25_INP_PATH="Bader/I25/${SITE_ID}/inp.ape"
  I100_DEN_NAME="${SITE_ID}-100"
  I75_DEN_NAME="${SITE_ID}-75"
  I50_DEN_NAME="${SITE_ID}-50"
  I25_DEN_NAME="${SITE_ID}-25"
  I100_DEN_NAME_temp="${SITE_ID}-100-temp"
  I75_DEN_NAME_temp="${SITE_ID}-75-temp"
  I50_DEN_NAME_temp="${SITE_ID}-50-temp"
  I25_DEN_NAME_temp="${SITE_ID}-25-temp"
  DEN_PATH="ae/density"
  rm -rf $I100_DEN_NAME_temp $I75_DEN_NAME_temp $I50_DEN_NAME_temp $I25_DEN_NAME_temp
  rm -rf $I100_DEN_NAME $I75_DEN_NAME $I50_DEN_NAME $I25_DEN_NAME
  #echo "Currently, value of i is: $i, site ID is: $SITE_ID, I100 inp file is: $I100_INP_PATH, I100 den output name is: $I100_DEN_NAME"
  if [ -f $I100_INP_PATH ]
  then
    echo "inp.ape file for 100% ionicity found!"
    cd $I100_DIRECTORY_PATH
    timeout 100 ape <inp.ape> out.ape
    cp $DEN_PATH $CURRENT_PATH/$I100_DEN_NAME_temp
    cd $CURRENT_PATH
    tail -n +8 $I100_DEN_NAME_temp > $I100_DEN_NAME
    rm -rf $I100_DEN_NAME_temp
  fi 

  if [ -f $I75_INP_PATH ]
  then
    echo "inp.ape file for 75% ionicity found!"
    cd $I75_DIRECTORY_PATH
    timeout 100 ape <inp.ape> out.ape
    cp $DEN_PATH $CURRENT_PATH/$I75_DEN_NAME_temp
    cd $CURRENT_PATH
    tail -n +8 $I75_DEN_NAME_temp > $I75_DEN_NAME
    rm -rf $I75_DEN_NAME_temp
  fi

  if [ -f $I50_INP_PATH ]
  then
    echo "inp.ape file for 50% ionicity found!"
    cd $I50_DIRECTORY_PATH
    timeout 100 ape <inp.ape> out.ape
    cp $DEN_PATH $CURRENT_PATH/$I50_DEN_NAME_temp
    cd $CURRENT_PATH
    tail -n +8 $I50_DEN_NAME_temp > $I50_DEN_NAME
    rm -rf $I50_DEN_NAME_temp
  fi

  if [ -f $I25_INP_PATH ]
  then
    echo "inp.ape file for 25% ionicity found!"
    cd $I25_DIRECTORY_PATH
    timeout 100 ape <inp.ape> out.ape
    cp $DEN_PATH $CURRENT_PATH/$I25_DEN_NAME_temp
    cd $CURRENT_PATH
    tail -n +8 $I25_DEN_NAME_temp > $I25_DEN_NAME
    rm -rf $I25_DEN_NAME_temp
  fi

  done
echo "DONE!"
